version: "3.8"
services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data